/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_seal139_jSwarm_backend_hip_HipDriver */

#ifndef _Included_io_github_seal139_jSwarm_backend_hip_HipDriver
#define _Included_io_github_seal139_jSwarm_backend_hip_HipDriver
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipGetVersion
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipGetVersion
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipEnumerateDevices
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipEnumerateDevices
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipGetDeviceInfo
	 * Signature: (I)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipGetDeviceInfo
	(JNIEnv*, jclass, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipGetDeviceName
	 * Signature: (I)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipGetDeviceName
	(JNIEnv*, jclass, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipAddQueue
	 * Signature: (I)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipAddQueue
	(JNIEnv*, jclass, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipDeleteQueue
	 * Signature: ([JI)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipDeleteQueue
	(JNIEnv*, jclass, jlongArray, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipCreateProgram
	 * Signature: (Ljava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipCreateProgram
	(JNIEnv*, jclass, jstring);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipDeleteProgram
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipDeleteProgram
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipGetKernel
	 * Signature: (JLjava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipGetKernel
	(JNIEnv*, jclass, jlong, jstring);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipLaunch
	 * Signature: (JJIIIIII[JI)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipLaunch
	(JNIEnv*, jclass, jlong, jlong, jint, jint, jint, jint, jint, jint, jlongArray, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipHook
	 * Signature: (J)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipHook
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipSyncDataTo
	 * Signature: (JJJJ)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipSyncDataTo
	(JNIEnv*, jclass, jlong, jlong, jlong, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipSyncDataFrom
	 * Signature: (JJJJ)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipSyncDataFrom
	(JNIEnv*, jclass, jlong, jlong, jlong, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipUnhook
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipUnhook
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_hip_HipDriver
	 * Method:    hipWaitAll
	 * Signature: ()I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_hip_HipDriver_hipWaitAll
	(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
