/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_seal139_jSwarm_runtime_datatype_FloatVector */

#ifndef _Included_io_github_seal139_jSwarm_runtime_datatype_FloatVector
#define _Included_io_github_seal139_jSwarm_runtime_datatype_FloatVector
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Hook
	 * Signature: ([F)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Hook
	(JNIEnv*, jclass, jfloatArray);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Unhook
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Unhook
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Construct
	 * Signature: (I)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Construct
	(JNIEnv*, jclass, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Delete
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Delete
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32GetSize
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32GetSize
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Sync
	 * Signature: (JJIIF)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Sync
	(JNIEnv*, jclass, jlong, jlong, jint, jfloat);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Fetch
	 * Signature: (JJII)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Fetch
	(JNIEnv*, jclass, jlong, jlong, jint, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32ContainsAll
	 * Signature: (J[F)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32ContainsAll
	(JNIEnv*, jclass, jlong, jfloatArray);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32GetByIndex
	 * Signature: (JI)F
	 */
	JNIEXPORT jfloat JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32GetByIndex
	(JNIEnv*, jclass, jlong, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32GetIndex
	 * Signature: (JF)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32GetIndex
	(JNIEnv*, jclass, jlong, jfloat);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32GetLastIndex
	 * Signature: (JF)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32GetLastIndex
	(JNIEnv*, jclass, jlong, jfloat);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Remove
	 * Signature: (JF)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Remove
	(JNIEnv*, jclass, jlong, jfloat);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32RemoveAll
	 * Signature: (J[F)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32RemoveAll
	(JNIEnv*, jclass, jlong, jfloatArray);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32RemoveByIndex
	 * Signature: (JI)F
	 */
	JNIEXPORT jfloat JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32RemoveByIndex
	(JNIEnv*, jclass, jlong, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Set
	 * Signature: (JIF)F
	 */
	JNIEXPORT jfloat JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Set
	(JNIEnv*, jclass, jlong, jint, jfloat);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Clear
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Clear
	(JNIEnv*, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
