/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_seal139_jSwarm_runtime_datatype_DoubleVector */

#ifndef _Included_io_github_seal139_jSwarm_runtime_datatype_Vector
#define _Included_io_github_seal139_jSwarm_runtime_datatype_Vector

#ifdef __cplusplus
extern "C" {
#endif

	// ------- Short --------
	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_ShortVector
	 * Method:    int16Construct
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_ShortVector_int16Construct
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_ShortVector
	 * Method:    int16Delete
	 * Signature: (J)J
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_ShortVector_int16Delete
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_ShortVector
	 * Method:    int16Size
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_ShortVector_int16Size
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_ShortVector
	 * Method:    int16Sync
	 * Signature: (J[SI)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_ShortVector_int16Sync
	(JNIEnv*, jclass, jlong, jshortArray, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_ShortVector
	 * Method:    int16Fetch
	 * Signature: (JII)[S
	 */
	JNIEXPORT jshortArray JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_ShortVector_int16Fetch
	(JNIEnv*, jclass, jlong, jint, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_ShortVector
	 * Method:    int16Contains
	 * Signature: (JS)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_ShortVector_int16Contains
	(JNIEnv*, jclass, jlong, jshort);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_ShortVector
	 * Method:    int16Remove
	 * Signature: (JS)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_ShortVector_int16Remove
	(JNIEnv*, jclass, jlong, jshort);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_ShortVector
	 * Method:    int16Clear
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_ShortVector_int16Clear
	(JNIEnv*, jclass, jlong);

	// ------ Integer -------
	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_IntegerVector
	 * Method:    int32Construct
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_IntegerVector_int32Construct
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_IntegerVector
	 * Method:    int32Delete
	 * Signature: (J)J
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_IntegerVector_int32Delete
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_IntegerVector
	 * Method:    int32Size
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_IntegerVector_int32Size
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_IntegerVector
	 * Method:    int32Sync
	 * Signature: (J[II)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_IntegerVector_int32Sync
	(JNIEnv*, jclass, jlong, jintArray, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_IntegerVector
	 * Method:    int32Fetch
	 * Signature: (JII)[I
	 */
	JNIEXPORT jintArray JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_IntegerVector_int32Fetch
	(JNIEnv*, jclass, jlong, jint, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_IntegerVector
	 * Method:    int32Contains
	 * Signature: (JI)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_IntegerVector_int32Contains
	(JNIEnv*, jclass, jlong, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_IntegerVector
	 * Method:    int32Remove
	 * Signature: (JI)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_IntegerVector_int32Remove
	(JNIEnv*, jclass, jlong, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_IntegerVector
	 * Method:    int32Clear
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_IntegerVector_int32Clear
	(JNIEnv*, jclass, jlong);

	// -------- long --------
	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_LongVector
	 * Method:    int64Construct
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_LongVector_int64Construct
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_LongVector
	 * Method:    int64Delete
	 * Signature: (J)J
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_LongVector_int64Delete
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_LongVector
	 * Method:    int64Size
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_LongVector_int64Size
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_LongVector
	 * Method:    int64Sync
	 * Signature: (J[JI)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_LongVector_int64Sync
	(JNIEnv*, jclass, jlong, jlongArray, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_LongVector
	 * Method:    int64Fetch
	 * Signature: (JII)[J
	 */
	JNIEXPORT jlongArray JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_LongVector_int64Fetch
	(JNIEnv*, jclass, jlong, jint, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_LongVector
	 * Method:    int64Contains
	 * Signature: (JJ)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_LongVector_int64Contains
	(JNIEnv*, jclass, jlong, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_LongVector
	 * Method:    int64Remove
	 * Signature: (JJ)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_LongVector_int64Remove
	(JNIEnv*, jclass, jlong, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_LongVector
	 * Method:    int64Clear
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_LongVector_int64Clear
	(JNIEnv*, jclass, jlong);

	// ------- Float --------
	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Construct
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Construct
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Delete
	 * Signature: (J)J
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Delete
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Size
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Size
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Sync
	 * Signature: (J[FI)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Sync
	(JNIEnv*, jclass, jlong, jfloatArray, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Fetch
	 * Signature: (JII)[F
	 */
	JNIEXPORT jfloatArray JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Fetch
	(JNIEnv*, jclass, jlong, jint, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Contains
	 * Signature: (JF)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Contains
	(JNIEnv*, jclass, jlong, jfloat);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Remove
	 * Signature: (JF)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Remove
	(JNIEnv*, jclass, jlong, jfloat);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_FloatVector
	 * Method:    fp32Clear
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_FloatVector_fp32Clear
	(JNIEnv*, jclass, jlong);

	// ------- Double -------
	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_DoubleVector
	 * Method:    fp64Construct
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_DoubleVector_fp64Construct
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_DoubleVector
	 * Method:    fp64Delete
	 * Signature: (J)J
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_DoubleVector_fp64Delete
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_DoubleVector
	 * Method:    fp64Size
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_DoubleVector_fp64Size
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_DoubleVector
	 * Method:    fp64Sync
	 * Signature: (J[DI)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_DoubleVector_fp64Sync
	(JNIEnv*, jclass, jlong, jdoubleArray, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_DoubleVector
	 * Method:    fp64Fetch
	 * Signature: (JII)[D
	 */
	JNIEXPORT jdoubleArray JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_DoubleVector_fp64Fetch
	(JNIEnv*, jclass, jlong, jint, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_DoubleVector
	 * Method:    fp64Contains
	 * Signature: (JD)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_DoubleVector_fp64Contains
	(JNIEnv*, jclass, jlong, jdouble);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_DoubleVector
	 * Method:    fp64Remove
	 * Signature: (JD)Z
	 */
	JNIEXPORT jboolean JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_DoubleVector_fp64Remove
	(JNIEnv*, jclass, jlong, jdouble);

	/*
	 * Class:     io_github_seal139_jSwarm_runtime_datatype_DoubleVector
	 * Method:    fp64Clear
	 * Signature: (J)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_runtime_datatype_DoubleVector_fp64Clear
	(JNIEnv*, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
