/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_seal139_jSwarm_backend_ocl_OclDriver */

#ifndef _Included_io_github_seal139_jSwarm_backend_ocl_OclDriver
#define _Included_io_github_seal139_jSwarm_backend_ocl_OclDriver
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclGetVersion
	 * Signature: ()Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclGetVersion
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclEnumerateDevices
	 * Signature: ()J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclEnumerateDevices
	(JNIEnv*, jclass);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclGetDeviceInfo
	 * Signature: (J)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclGetDeviceInfo
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclGetDeviceName
	 * Signature: (J)Ljava/lang/String;
	 */
	JNIEXPORT jstring JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclGetDeviceName
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclCreateContext
	 * Signature: (J)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclCreateContext
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclDeleteContext
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclDeleteContext
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclAddQueue
	 * Signature: (JJI)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclAddQueue
	(JNIEnv*, jclass, jlong, jlong, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclDeleteQueue
	 * Signature: ([JI)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclDeleteQueue
	(JNIEnv*, jclass, jlongArray, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclCreateProgram
	 * Signature: (JJLjava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclCreateProgram
	(JNIEnv*, jclass, jlong, jlong, jstring);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclDeleteProgram
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclDeleteProgram
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclGetKernel
	 * Signature: (JLjava/lang/String;)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclGetKernel
	(JNIEnv*, jclass, jlong, jstring);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclDeleteKernel
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclDeleteKernel
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclLaunch
	 * Signature: (JJIIIIII[JI)V
	 */
	JNIEXPORT void JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclLaunch
	(JNIEnv*, jclass, jlong, jlong, jint, jint, jint, jint, jint, jint, jlongArray, jint);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclHook
	 * Signature: (JJ)J
	 */
	JNIEXPORT jlong JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclHook
	(JNIEnv*, jclass, jlong, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclSyncDataTo
	 * Signature: (JJJJ)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclSyncDataTo
	(JNIEnv*, jclass, jlong, jlong, jlong, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclSyncDataFrom
	 * Signature: (JJJJ)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclSyncDataFrom
	(JNIEnv*, jclass, jlong, jlong, jlong, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclUnhook
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclUnhook
	(JNIEnv*, jclass, jlong);

	/*
	 * Class:     io_github_seal139_jSwarm_backend_ocl_OclDriver
	 * Method:    oclWaitAll
	 * Signature: ([JI)I
	 */
	JNIEXPORT jint JNICALL Java_io_github_seal139_jSwarm_backend_ocl_OclDriver_oclWaitAll
	(JNIEnv*, jclass, jlongArray, jint);

#ifdef __cplusplus
}
#endif
#endif
